### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [myst6re/hyne#12]
i've downloaded Version '1.9.2c' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the **CFBundleVersion** and **CFBundleShortVersionString** entries in your **Info.plist** file are missing.
all apps on macOS are supposed to contain valid version information.

**Comment by core-code** [comment]
sorry but i can confirm this is NOT fixed in 1.9.3

both the CFBundleVersion and CFBundleShortVersionString entries are still missing from the Info.plist

even if they were there, you wouldn't see the the version number in the Finder, because the 'CFBundleGetInfoString' key would override them. this key has been deprecated for more than 10 years and should be removed.

attached screenshots of Info.plist without the right keys and GetInfo from Finder

<img width="480" alt="screen shot 2018-10-14 at 11 27 28" src="https://user-images.githubusercontent.com/1261954/46914911-763b8b00-cfa4-11e8-9fea-24473db55ad1.png">
<img width="191" alt="screen shot 2018-10-14 at 11 27 49" src="https://user-images.githubusercontent.com/1261954/46914912-76d42180-cfa4-11e8-8fdb-a18b2ff39868.png">

**Comment by myst6re** [comment]
Ok, thanks. I will test different qmake variables this week on my Mac. If Qt does not know how to generate a good plist file, I will generate it myself.

**Comment by core-code** [comment]
awesome thanks

**Comment by myst6re** [comment]
I rewrote Info.plist, here the generated version:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>CFBundleExecutable</key>
        <string>Hyne</string>
        <key>CFBundleIconFile</key>
        <string>hyne.icns</string>
        <key>CFBundleIdentifier</key>
        <string>com.yourcompany.Hyne</string>
        <key>CFBundleShortVersionString</key>
        <string>1.9</string>
        <key>CFBundleVersion</key>
        <string>1.9.3</string>
        <key>CFBundlePackageType</key>
        <string>APPL</string>
        <key>LSMinimumSystemVersion</key>
        <string>10.11</string>
        <key>NSPrincipalClass</key>
        <string>NSApplication</string>
        <key>NSSupportsAutomaticGraphicsSwitching</key>
        <true/>
</dict>
</plist>
```

There nothing more to add?

**Comment by core-code** [comment]
hey. looks quite good already. 

1.) i am not sure why you are setting the CFBundleShortVersionString to just 1.9. 'short' does mean you should omni part of the version (except build numbers which the user probably shouldn't see). its more of an historic artefact because once-upon-a-time there was 'CFBundleLongVersionString'. i'd recommend setting it to 1.9.3 too.

2.) i've compared the list of keys you have in there with the default Info.plist that Xcode 10.0 generates for a new project. these ones are in there additionally:
```

	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2018 MYCOOLCOMPANY. All rights reserved.</string>

```

**Comment by myst6re** [comment]
I created a new pull request. The NSHumanReadableCopyright entry seems not appliable on this project.
