### ISSUE TITLE
macOS release is missing qt5

### ISSUE THREAD

**Issue by thomasmichaelwallace** [myst6re/hyne#17]
Hi,

Thanks for the great application!

Since hyne moved to QT5 (v1.10) it looks like you're not longer bundling QT5, which means that the downloaded release doesn't work.

It's fine if you compile it yourself (just in case someone else has this problem):

```
brew install qt5
export PATH=$PATH:/usr/local/Cellar/qt/5.14.0/bin
qmake
make
cp hyne_en.qm ./Hyne.app/Contents/MacOS
```

But I'm guessing travis needs to be configured to bundle QT5 on MacOS?

**Comment by myst6re** [comment]
Travis works, but deploy fails. I need to modify secret tokens in .travis.yml file... again... and again...

So yeah I built it myself, and forget that MacOS version needs a static build.

**Comment by myst6re** [comment]
Err, I just forgot to run `macdeployqt`. I upload a new archive right now 👍

**Comment by thomasmichaelwallace** [comment]
Awesome - thanks :)
