### ISSUE TITLE
Possible to add Nintendo Switch Save?

### ISSUE THREAD

**Issue by CroCop86** [myst6re/hyne#18]
Hi,

would it be possible to add Nintendo Switch savegame support please?

**Comment by myst6re** [comment]
A save file from a Switch was sent to me, but I don't understant the compression algorithm.

**Comment by CroCop86** [comment]
Hmm i understand, thanks for your answer. Maybe this could help you?
https://gbatemp.net/threads/has-anyone-been-able-to-get-hyne-to-work-with-final-fantasy-8-remastered.547364/#post-8778448
It's an workaround with Hexediting the first 4 Bytes. I have managed to convert it, but a Saveeditor would be really great.

Turtle Insect created a converting tool, it's working from switch to pc, but i was not able to convert it back to switch. Maybe this could help you too?

**Comment by myst6re** [comment]
Thank you, I made a PR #19

**Comment by CroCop86** [comment]
Fantastic, thank you :)
