### ISSUE TITLE
FF8 Switch Saves don't load.

### ISSUE THREAD

**Issue by onefourthreeNX** [myst6re/hyne#21]
I loaded FF8 1.0.0, deleted all my saves from the switch, then started a new save.

I used Checkpoint to backup my save, transferred to PC, then loaded with the new hyne.

When I load it, it says:
![image](https://user-images.githubusercontent.com/48222684/73129023-945dac80-3f97-11ea-81e2-83d3578c79a3.png)

**Comment by myst6re** [comment]
Hello,
Can you share your files here? I'll take a look
