### ISSUE TITLE
metadata ended prematurely

### ISSUE THREAD

**Issue by benny4556** [myst6re/hyne#24]
Above all, thanks for the awesome work you guys done here!

I see that you guys dropped the Linux version at 1.8.1 and therefore, we cannot use it for the old version of the game anymore (since it doesn't handle the metadata.xml). I tried using the 1.11.1 version on Linux with Wine and it kinda works, but with several problems.

Even though my savefiles are in the "canonical" directory (from a wine perspective) Hyne fails to find them. I have to manually open each savefile. I can edit them, but Hyne fails to write the metadata with "premature end" error. I guess it doesn't even find it. Could you guys maybe just add an option allowing one to set the path where the savefiles should be (including metadata.xml)?

**Comment by myst6re** [comment]
Sure I can :-)

**Comment by sithlord48** [comment]
Hyne should be having a continuous appimage built for linux.

**Comment by myst6re** [comment]
The last (experimental) version of Hyne for Linux can be found here in AppImage format: https://github.com/myst6re/hyne/releases/tag/continuous

**Comment by benny4556** [comment]
yeps, that solves all problems. Thanks!

**Comment by benny4556** [comment]
Okay, I guess that that was premature...!
If I try to bring a savefile from FF8 Remastered into the old FF8, I still get the "metadata ended prematurely" error. Is that part even supposed to work?

**Comment by benny4556** [comment]
There was a missing </gamestatus> at the end... weird, since I never changed the file manually.

**Comment by myst6re** [comment]
Yeah that strange :/ I check why it could happen

**Comment by myst6re** [comment]
Please try this version: https://github.com/myst6re/hyne/releases/tag/continuous

**Comment by myst6re** [comment]
Closed with version 1.11.2
