### ISSUE TITLE
retroarch compatibility

### ISSUE THREAD

**Issue by davcri** [myst6re/hyne#3]
Can retroarch compatibility be added ?

I was playing using retroarch's pcsxrearmed that uses `.srm` saves.
__hyne__ seems to does not support them, but I succesfully used it using these steps: 
- rename `.srm` saves into `.mcr`
- use hyne to edit saves
- rename `.mcr` back to `.srm`

**Comment by sithlord48** [comment]
the .srm files used by retroarch are mcr files, srm would only need to be added to the file filters to enable loading them directly.

**Comment by davcri** [comment]
I thought the same thing :smile:

**Comment by sithlord48** [comment]
i have done this for Black Chocobo a FF7 save editor i write.. works perfectly fine w/ the srm files after adding it to the list.. i will see how its handled in hyne and see if i can get something ready for myst's next release

**Comment by myst6re** [comment]
I tried memcardrex recently and saw lot of new formats, incompatible with Hyne.
