### ISSUE TITLE
1.9.1 release for mac osx

### ISSUE THREAD

**Issue by vin047** [myst6re/hyne#7]
Hi, 
I was able to compile a release of 1.9.1 for Mac OSX. Confirmed working in El Capitan (latest OSX release). Would it be possible to add this to the 1.9.1 release tag? 
Thanks

[Hyne-1.9.1-macos.zip](https://github.com/myst6re/hyne/files/201642/Hyne-1.9.1-macos.zip)

**Comment by myst6re** [comment]
Hello, can you specify how to install dependencies on Mac OSX? It seems that your build does not contains Qt.

**Comment by vin047** [comment]
Sorry about that, completely forgot! Here's the app with Qt bundled.

[Hyne-1.9.1-macos.zip](https://github.com/myst6re/hyne/files/203309/Hyne-1.9.1-macos.zip)

**Comment by myst6re** [comment]
Ok, I added this build in the last release, thanks! Next time it will be added automatically by Travis.
