### ISSUE TITLE
How do I compline in English?

### ISSUE THREAD

**Issue by mcred** [myst6re/hyne#8]
I'm compiling v 1.9.2 in OSX without errors. How do I set the default language to be English? When I download a precompiled version, English is default. When I compile, it is always French. Everything is working, I just can't see how to set English as the default language. Any help is appreciated.

**Comment by sithlord48** [comment]
On mac os you need to put the language files that are generated in the app bundle 
they need to go in  (iirc )  Hyne.app/contents/MacOs (with the hyne execuitable) 
The generated language files are the ones with the .qm extentions.
After you have installed the language files in the correct location you should see more entries for languages (as that menu is automaticly populated based on the found translations) 

 Hope that helps you out .

**Comment by mcred** [comment]
I see hyne_en.ts, but not hyne_en.qm in the project folder. I was able to copy the hyne_en.qm file from a downloaded version, but it did not change the menu language from French. Is there a way for me to generate .qm files and set the initial language to English? The top menu language.

**Comment by sithlord48** [comment]
that should have happened as part of the build step it runs lrelease for you . but you can do it manually just load the ts file in to QtLinguist and use the Release option it will generate the qm file  with that step. you will still need to load them into hyne.. 

French is and will always be the default language as that is the language the strings are in the code as. hyne will remember your setting and load the language file you picked last. so after you have the languages installed you will still need to pick english from the list then restart hyne.

**Comment by mcred** [comment]
I think I'm missing some steps beyond what's in the ReadMe. I'm compiling from my CLI. I'm running ```qmake```, then ```make``` and it works, just in French. 

After running ```qmake -config release``` it is mostly in English and the application is using the English language file. This works for me!

Thank you for the help!
